"""Add product fields

Revision ID: 4251b9c6cbbe
Revises: 591d700e7c83
Create Date: 2026-08-03 00:15:56.648498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4251b9c6cbbe'
down_revision = '591d700e7c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('minimum_stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(
            "uq_products_code",
            ["code"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_products_code",
            type_="unique"
        )
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('active')
        batch_op.drop_column('location')
        batch_op.drop_column('minimum_stock')
        batch_op.drop_column('quantity')
        batch_op.drop_column('description')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
