"""Add categories

Revision ID: aedd8739f8aa
Revises: a0b4c52c839c
Create Date: 2026-09-22 11:26:47.370839

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aedd8739f8aa"
down_revision = "a0b4c52c839c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "categories",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    with op.batch_alter_table(
        "products",
        schema=None,
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "category_id",
                sa.Integer(),
                nullable=True,
            )
        )

        batch_op.create_foreign_key(
            "fk_products_category_id",
            "categories",
            ["category_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        "products",
        schema=None,
    ) as batch_op:

        batch_op.drop_constraint(
            "fk_products_category_id",
            type_="foreignkey",
        )

        batch_op.drop_column(
            "category_id",
        )

    op.drop_table(
        "categories",
    )

    # ### end Alembic commands ###
