"""Add previous quantity to stock movements

Revision ID: b84c8174c0c4
Revises: 534d915c4a96
Create Date: 2026-08-15 15:46:42.251405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84c8174c0c4'
down_revision = '534d915c4a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('previous_quantity')

    # ### end Alembic commands ###
